import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { DockNav } from "@/components/navigation/DockNav";
import { ThemeProvider } from "@/components/theme/ThemeProvider"
import { Candal, Sriracha, Satisfy } from "next/font/google";

const candal = Candal({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-candal',
});

const sriracha = Sriracha({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-sriracha',
});

const satisfy = Satisfy({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-satisfy',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${candal.variable} ${sriracha.variable} ${satisfy.variable} font-sriracha antialiased min-h-screen bg-[#F2F6D0] dark:bg-[#443627]`}>
        <ThemeProvider>
          <DockNav />
          <main className="min-h-screen">
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
